version: '2.1'
services:
  db:
    image: mydb
    # ports:
    #   - 3306
    networks:
      - back-tier
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=rootpasswd --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

    
  register:
    image: h4-register
    # ports:
    #   - 8088:80
    networks:
      # - front-tier
      - back-tier
    links:
      - db
    # volumes:
    #   - "./:/go/go-gin-example"
    depends_on:
      - db
      
  login:
    image: h4-register
    # ports:
    #   - 8089:80
    networks:
      - back-tier
    links:
      - db
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - 80:80
    links:
      - register
      - login
    networks:
      - back-tier
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/ssl:/etc/nginx/ssl"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    depends_on:
      - register
      - login
    
networks:
  back-tier:
    driver: bridge
